export const iconfontList: string[] = [
  'icon-biaojiyihuishou',
  'icon-biaodansheji',
  'icon-bumenguanli',
  'icon-chakan',
  'icon-cheliangguanli',
  'icon-caidanguanli',
  'icon-daochu',
  'icon-daimashengcheng',
  'icon-bianji',
  'icon-daoru',
  'icon-fuwujiankong',
  'icon-huchifuwu',
  'icon-huancunjiankong',
  'icon-fenpeiquanxian',
  'icon-liuliangjiankong',
  'icon-jiekouwendang',
  'icon-liexianyin',
  'icon-dongtailuyou',
  'icon-lingpaiguanli',
  'icon-sousuo',
  'icon-suoping',
  'icon-quxiaoyuyue',
  'icon-meiyoucuowurizhi',
  'icon-quanxianguanli',
  'icon-shanchu',
  'icon-shuaxin',
  'icon-shouqi',
  'icon-rizhiguanli',
  'icon-tianjia',
  'icon-wangdianzhanghao',
  'icon-xitongjiankong',
  'icon-xiangqing',
  'icon-wendangkuozhan',
  'icon-weixingongzhonghao',
  'icon-wangdianzhanghaozhongzhimima',
  'icon-wangdianguanli',
  'icon-yuyueguanli',
  'icon-zantingyingyeshijian',
  'icon-yuyuedan',
  'icon-yuyueshijian',
  'icon-zhongduanguanli',
  'icon-zhijiandan',
  'icon-zidianguanli',
  'icon-zidianxiang',
  'icon-zhankai',
  'icon-fuwukaquan',
  'icon-fuwudingdan',
  'icon-dingdanguanli',
  'icon-canshuguanli',
  'icon-guanlianfuwukaquan',
  'icon-kaquanguanli',
  'icon-jiaoseguanli',
  'icon-kaquanfafang',
  'icon-peizhiguanli',
  'icon-kaifapingtai',
  'icon-peizhiguanli1',
  'icon-shangjia',
  'icon-wenjianguanli',
  'icon-tesezhuti',
  'icon-zhutise',
  'icon-shujuyuanguanli',
  'icon-xiajia',
  'icon-xitongguanli',
  'icon-zuo',
  'icon-you',
  'icon-miyueguanli',
  'icon-bannerpeizhi',
  'icon-yonghuguanli',
  'icon-quanping',
  'icon-tuichuquanping'
]

export const iconfontScriptUrl = 'https://at.alicdn.com/t/c/font_4147131_bxs7eicsxvp.js?spm=a313x.7781069.1998910419.54&file=font_4147131_bxs7eicsxvp.js'


// 获取阿里云所有 icon 标题的脚本
// const allIconfont = document.querySelectorAll('.project-iconlist .block-icon-list.clearfix li')
// let res = ''
// allIconfont.forEach(item => {
//   const title = item.querySelector('.icon-code.icon-code-show').innerHTML
//   res += `,'${title}'`
//   return title
// })
// console.log(res);
